import React from 'react';
import { Navigation, Footer } from '@/components/ui';

const Terms: React.FC = () => {
  return (
    <div className="min-h-screen bg-ctp-base text-ctp-text flex flex-col">
      <Navigation />

      <main className="flex-1 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="space-y-8">
          <div className="text-center">
            <h1 className="text-4xl font-bold bg-gradient-to-r from-ctp-blue via-ctp-mauve to-ctp-pink bg-clip-text text-transparent mb-4">
              Terms of Service
            </h1>
            <p className="text-ctp-subtext1">
              Last updated: January 2025
            </p>
          </div>

          <div className="prose prose-invert max-w-none space-y-8">
            <section>
              <h2 className="text-2xl font-semibold text-ctp-text mb-4">Acceptance of Terms</h2>
              <p className="text-ctp-subtext1 leading-relaxed">
                By accessing and using AgentSOLVR, you accept and agree to be bound by the terms and provision of this agreement.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ctp-text mb-4">Description of Service</h2>
              <p className="text-ctp-subtext1 leading-relaxed">
                AgentSOLVR is a voice-controlled AI development platform that helps users create software through natural language commands. 
                The service includes AI agents that assist with coding, testing, and deployment of applications.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ctp-text mb-4">User Accounts</h2>
              <ul className="space-y-2 text-ctp-subtext1">
                <li>• You must provide accurate and complete information when creating an account</li>
                <li>• You are responsible for maintaining the security of your account</li>
                <li>• You must notify us immediately of any unauthorized access to your account</li>
                <li>• One person or legal entity may not maintain more than one free account</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ctp-text mb-4">Acceptable Use</h2>
              <div className="space-y-4">
                <div>
                  <h3 className="text-lg font-medium text-ctp-text mb-2">You may use AgentSOLVR to:</h3>
                  <ul className="space-y-1 text-ctp-subtext1">
                    <li>• Create legitimate software applications and websites</li>
                    <li>• Develop tools for personal or commercial use</li>
                    <li>• Learn and experiment with AI-powered development</li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-lg font-medium text-ctp-text mb-2">You may not use AgentSOLVR to:</h3>
                  <ul className="space-y-1 text-ctp-subtext1">
                    <li>• Create malicious software, viruses, or malware</li>
                    <li>• Develop applications that violate laws or regulations</li>
                    <li>• Attempt to reverse engineer or compromise our AI systems</li>
                    <li>• Share account credentials or resell access to the service</li>
                  </ul>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ctp-text mb-4">Intellectual Property</h2>
              <p className="text-ctp-subtext1 leading-relaxed">
                You retain ownership of the code and applications you create using AgentSOLVR. AgentSOLVR retains 
                ownership of its platform, AI models, and proprietary technology. The code generated by our AI agents 
                is provided to you under a permissive license for your use.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ctp-text mb-4">Payment and Billing</h2>
              <ul className="space-y-2 text-ctp-subtext1">
                <li>• Subscription fees are billed in advance on a monthly or annual basis</li>
                <li>• All payments are non-refundable except as required by law</li>
                <li>• We may change our pricing with 30 days notice to existing subscribers</li>
                <li>• Accounts may be suspended for non-payment</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ctp-text mb-4">Limitation of Liability</h2>
              <p className="text-ctp-subtext1 leading-relaxed">
                AgentSOLVR is provided "as is" without warranty of any kind. We are not liable for any damages arising 
                from your use of the service, including but not limited to direct, indirect, incidental, or consequential damages.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ctp-text mb-4">Termination</h2>
              <p className="text-ctp-subtext1 leading-relaxed">
                Either party may terminate this agreement at any time. Upon termination, your access to AgentSOLVR will 
                cease, but you retain ownership of any code you created using our platform.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-ctp-text mb-4">Contact Us</h2>
              <p className="text-ctp-subtext1 leading-relaxed">
                If you have any questions about these Terms, please contact us at{' '}
                <a href="mailto:legal@agentsolvr.com" className="text-ctp-blue hover:underline">
                  legal@agentsolvr.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Terms;