# AgentSOLVR Electron Build & Release - Simplified Version
# Builds from files in this repository (no private repo access needed)
name: Build & Release - Simple

on:
  release:
    types: [created]
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win32
            arch: x64
            artifact_name: windows
            
          - os: ubuntu-latest
            platform: linux
            arch: x64
            artifact_name: linux
            
          - os: macos-latest
            platform: darwin
            arch: x64
            artifact_name: macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: agentsolvr/package.json
        
    - name: Install dependencies
      run: |
        cd agentsolvr
        npm install --ignore-scripts
        
    - name: Build frontend
      run: |
        cd agentsolvr/frontend
        npm install
        npm run build
        
    - name: Build Electron app
      run: |
        cd agentsolvr
        npm run dist:${{ matrix.platform == 'win32' && 'win' || matrix.platform == 'darwin' && 'mac' || 'linux' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CSC_IDENTITY_AUTO_DISCOVERY: false
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}-build
        path: |
          agentsolvr/dist/*.exe
          agentsolvr/dist/*.dmg
          agentsolvr/dist/*.AppImage
          agentsolvr/dist/*.deb
          agentsolvr/dist/*.rpm
        if-no-files-found: warn
        
