# Test GitHub Actions - Quick test to see if Actions work on this account
name: Test Actions

# Trigger on any push to test immediately
on:
  push:
    branches: [ master ]
  workflow_dispatch: # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test basic functionality
      run: |
        echo "🧪 Testing GitHub Actions..."
        echo "Repository: ${{ github.repository }}"
        echo "Event: ${{ github.event_name }}"
        echo "Actor: ${{ github.actor }}"
        echo "✅ GitHub Actions is working!"
        
    - name: Check if this is public repo
      run: |
        echo "Repository visibility should be public for free Actions"
        echo "If you see this message, Actions are working! 🎉"
        
    - name: Test step completion
      run: |
        echo "🎯 Test completed successfully!"
        echo "Ready to proceed with Electron build automation."